name:                aeson-default
version:             0.9.1.0
synopsis:            Apply default value to FromJSON instances' Maybe fields
description:         Please see http://hackage.haskell.org/package/aeson-default
github:              versioncloud/aeson-default
category:            HKD, Default, JSON, Library
license:             BSD3
author:              Jorah Gao
maintainer:          jorah@version.cloud
copyright:           Copyright (c) 2020 Version Cloud

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- aeson >= 1.2 && < 2
- base >= 4.9 && < 5
- containers >= 0.5.10 && < 1

library:
  source-dirs: src
  other-modules:
  - Data.Aeson.Default.Class

tests:
  aeson-default-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O0
    dependencies:
    - aeson-default
